[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name="code_ra"
version="0.0.1"
authors = [
    {name = "Malakai Spann", email = "malakai.spann@red-alpha.com"}
]
description = "A set of utility functions and classes for the CodeRA program"
